apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: defi-providers-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 1G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defi-providers-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      component: defi-providers-redis
  template:
    metadata:
      labels:
        component: defi-providers-redis
    spec:
      containers:
      - name: defi-providers-redis
        image: redis:7
        imagePullPolicy: Always
        args: ["--requirepass", "$(REDIS_PASSWORD)"]
        resources:
          requests:
            cpu: 10m
            memory: 130Mi
          limits:
            memory: 130Mi
        ports:
          - name: redis-port
            containerPort: 6379
        env:
        - name: MASTER
          value: "true"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: defi-providers-secrets
              key: REDIS_PASSWORD
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: defi-providers-redis-pvc
  strategy: # temporary hack around "ReadWriteOnce" access mode issue (https://stackoverflow.com/a/62230273/4725013)
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: defi-providers-redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis-port
      protocol: TCP
  selector:
    component: defi-providers-redis
